Java Web Lab/J3.L.P0004_DigitalNews/src/java/entity/Article.java
package entity;

import java.sql.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author MSI
 */
public class Article {
    
    private int id;
    private String title;
    private String image;
    private String content;
    private Date uploadDate;
    private String author;

    public Article(int id, String title, String image, String content, Date uploadDate, String author) {
        this.id = id;
        this.title = title;
        this.image = image;
        this.content = content;
        this.uploadDate = uploadDate;
        this.author = author;
    }

    public Article() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getShortcut() {
        String shortcut;
        if (content.length() > 100) shortcut = content.substring(0, 100)+"...";
        else shortcut = content;
        return shortcut;
    }
    
    public String getFormatDate() {
        SimpleDateFormat monthFormat = new SimpleDateFormat("MMM");
        String monthStr = monthFormat.format(uploadDate);
        return monthStr + " " + new SimpleDateFormat(" dd yyyy - hh:mmaaa").format(uploadDate).toLowerCase();
    }
    
    public String getAuthorLine() {
        return "By " + author + " | " + getFormatDate();
    }
    
}

Java Web Lab/J3.L.P0004_DigitalNews/src/java/control/SearchController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control;

import entity.Article;
import java.io.IOException;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import model.HomeDAO;
import model.SearchDAO;

/**
 *
 * @author MSI
 */
public class SearchController extends HttpServlet {

    
    private int[] getPageFromTo(int currentPage, int totalNumOfPage) {
        int numOfDisplayPage = 3;
        int pageTo,pageFrom;
        pageFrom = currentPage;
        pageTo = currentPage + numOfDisplayPage - 1;
        if (pageTo > totalNumOfPage) {
            pageTo = totalNumOfPage;
            pageFrom = pageTo - numOfDisplayPage + 1;
        }
        if (pageFrom < 1) {
            pageFrom = 1;
        }
        return new int[]{pageFrom,pageTo};
    }
    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        SearchDAO dao = new SearchDAO();
        try {
            String keyword = request.getParameter("keyword");
            String currentPageStr = request.getParameter("currentPage");
            if (keyword != null && !keyword.isEmpty()) {
                int currentPage;
                //user click search
                if (currentPageStr == null) {
                    currentPage = 1;
                //user click on page number
                } else if (!currentPageStr.matches("\\d+")) {
                    currentPage = 0;
                } else {
                    currentPage = Integer.parseInt(currentPageStr);
                }

                List<Article> searchList = dao.getSearchListByPageNumber(currentPage, keyword);
                int numOfPage = dao.getNumberOfPage(keyword);
                
                int[] pageFromTo = getPageFromTo(currentPage, numOfPage);
                
                request.setAttribute("searchList", searchList);
                request.setAttribute("numOfPage", numOfPage);
                request.setAttribute("currentPage", currentPage);
                request.setAttribute("pageFrom", pageFromTo[0]);
                request.setAttribute("pageTo", pageFromTo[1]);
                request.setAttribute("keyword", keyword);
            }
            HomeDAO homedao = new HomeDAO();
            List<Article> last5List = homedao.getTop5RecentArticles();
            request.setAttribute("last5List", last5List);
            request.setAttribute("lastArticle", last5List.get(0));

        } catch (NumberFormatException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        request.getRequestDispatcher("search.jsp").forward(request, response);
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Java Web Lab/J3.L.P0004_DigitalNews/web/header.jsp
<%-- 
    Document   : header
    Created on : Sep 17, 2019, 8:26:13 PM
    Author     : MSI
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <body>
        <div class="no-collapse">
            <div class="preheader no-repeat"></div>
            <div class="header no-collapse no-repeat">
                <p class="font-sans title pt-025 pl-5 font-bold white">My Digital News</p>
            </div>
            <!-- Navigation -->
            <div class="navigation no-repeat flex">
                <a href="home" class="ml-5 a-reset pointer"><p class="font-sans menu-child mt-05 font-bold white">News</p></a>
            </div>
        </div>
    </body>
</html>

Java Web Lab/J3.L.P0004_DigitalNews/web/index.jsp
<%-- 
    Document   : index
    Created on : Sep 16, 2019, 4:07:15 PM
    Author     : MSI
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" type="text/css" href="public/css/common.css">
        <link rel="stylesheet" type="text/css" href="public/css/lib.css">
        <title>Home</title>
    </head>
    <body>
        <!-- Main Wrapper -->
        <div class="main-wrapper no-collapse">
            <!-- Header -->
            <%@include file="header.jsp" %>
            <!-- Main Body -->
            <div class="main-body no-collapse flex pt-05 pr-4 pb-1">
                <c:if test="${exception!=null}" var="isException">
                    <p class="title-article font-sans font-bold ml-5">${exception.message}</p>
                </c:if>
                <c:if test="${!isException}">
                    <!-- Left -->
                    <div class="left pl-5 pr-1">
                        <p class="title-article font-sans font-bold">${displayArticle.title}</p>
                        <img class="img-article" src="${displayArticle.image}">
                        <p class="content-article font-sans pb-1">${displayArticle.content}</p>
                        <p class="author-article font-sans pt-05"><img class="pr-05 author-img">
                            ${displayArticle.authorLine}</p>
                    </div>
                    <!-- Right -->
                    <%@include file="right-div.jsp" %>
                </c:if>
            </div>
            <!-- Footer -->
            <div class="footer no-repeat">
            </div>
        </div>
        <!-- End of Main Wrapper -->
    </body>
</html>

Java Web Lab/J3.L.P0004_DigitalNews/web/right-div.jsp
<%-- 
    Document   : right-div
    Created on : Sep 17, 2019, 8:26:03 PM
    Author     : MSI
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <body>
        <div class="right pl-1 no-collapse">
            <p class="title-article font-sans font-bold">Digital News</p>
            <p class="content-article font-sans mb-025">${lastArticle.shortcut}</p>
            <p class="title-article font-sans font-bold mt-05 mb-025">Search</p>
            <form class="mt-05" action="search" method="GET" autocomplete="on" >
                <input type="text" name="keyword" class="search-box">
                <input type="submit" value="Go" class="submit-bt font-sans ml-025">
            </form>
            <p class="title-article font-sans font-bold mt-1 mb-025">Last Articles</p>
            <c:forEach items="${last5List}" var="a">
                <a class="a-reset pointer font-sans" href="home?id=${a.id}">
                    <p class="recent-5-articles underline">${a.title}</p>
                </a>
            </c:forEach>
        </div>
    </body>
</html>

Java Web Lab/J3.L.P0004_DigitalNews/web/search.jsp
<%-- 
    Document   : search.jsp
    Created on : Sep 18, 2019, 11:16:11 AM
    Author     : MSI
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Search</title>
        <link rel="stylesheet" type="text/css" href="public/css/common.css">
        <link rel="stylesheet" type="text/css" href="public/css/lib.css">
    </head>
    <body>
        <!-- Main Wrapper -->
        <div class="main-wrapper no-collapse">
            <!-- Header -->
            <%@include file="header.jsp" %>
            <!-- Main Body -->
            <div class="main-body no-collapse flex pt-05 pr-4 pb-1">
                <!-- Left -->
                <div class="left pl-5 pr-1 flex-col">
                    <c:choose>
                        <%-- when user enter go-to-page on url and it is 0 or not number--%>
                        <c:when test="${currentPage == 0}">
                            <p class="title-article font-sans font-bold">
                                Go-to-page must be a positive number and not exceed total number of
                                found pages.
                            </p>
                        </c:when>
                        <%-- when not found any articles match keyword --%>
                        <c:when test="${numOfPage==0}">
                            <p class="title-article font-sans font-bold">No articles found.</p>
                        </c:when>
                        <%-- when user enter go-to-page on url and it exceeds number of found pages--%>
                        <c:when test="${currentPage>numOfPage}">
                            <p class="title-article font-sans font-bold">Exceed number of found pages.</p>
                        </c:when>
                        <%-- when there are found articles and to-page in range --%>
                        <c:when test="${numOfPage > 0}">
                            <c:forEach items="${searchList}" var="article">
                                
                                    <div class="mb-4 font-sans">
                                        <a class="a-reset pointer" href="home?id=${article.id}">
                                        <p class="title-article font-bold underline">${article.title}</p>
                                        </a>
                                        <img class="img-shortcut mr-1 mb-1" src="${article.image}">
                                        ${article.shortcut}
                                    </div>
                                
                            </c:forEach>
                            <center>
                                <a class="ma-05 a-reset font-sans" href="search?keyword=${keyword}&currentPage=${currentPage-1}">
                                    <span class="black">Page </span>
                                </a>
                                <c:if test="${currentPage > 1}">
                                    <a class="ma-05 a-reset font-sans" href="search?keyword=${keyword}&currentPage=${currentPage-1}">
                                        <span class="black font-bold"><</span>
                                    </a>
                                </c:if>
                                <c:forEach var="pageNum" begin="${pageFrom}" end="${pageTo}">
                                    <c:if test="${pageNum==currentPage}" var="isCurPage">
                                        <span class="ma-05 font-bold font-sans">${currentPage}</span>
                                    </c:if>
                                    <c:if test="${!isCurPage}">
                                        <a class="ma-05 a-reset font-sans" href="search?keyword=${keyword}&currentPage=${pageNum}">
                                            <span class="underline black">${pageNum}</span>
                                        </a>
                                    </c:if>
                                </c:forEach>
                                <c:if test="${currentPage < numOfPage}">
                                    <a class="ma-05 a-reset font-sans" href="search?keyword=${keyword}&currentPage=${currentPage+1}">
                                        <span class="black font-bold">></span>
                                    </a>
                                </c:if>
                            </center>
                        </c:when>
                        <%-- not enter keyword --%>
                        <c:otherwise>
                            <p class="title-article font-sans font-bold">Make sure you have entered keyword.</p>
                        </c:otherwise>
                    </c:choose>
                </div>
                <!-- Right -->
                <%@include file="right-div.jsp" %>
            </div>
            <div class="footer"></div>
        </div>
        <!-- End of Main Wrapper -->
    </body>
</html>